# Generated by Django 6.0.5 on 2026-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=100, verbose_name='Unvan (Title)')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Alt Başlık (Sub Title)')),
                ('description', models.TextField(verbose_name='Hakkımda Kısa Açıklama')),
                ('profile_image', models.ImageField(upload_to='profile/', verbose_name='Profil Fotoğrafı')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter / X Linki')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Linki')),
            ],
            options={
                'verbose_name': 'Genel Ayar',
                'verbose_name_plural': 'Genel Ayarlar',
            },
        ),
    ]
