# Generated by Django 6.0.5 on 2026-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='profile_image',
            field=models.CharField(max_length=255, verbose_name='Profil Fotoğrafı'),
        ),
    ]
