# Generated by Django 6.0.5 on 2026-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0002_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(max_length=254, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=254, verbose_name='Unvan (Örn: Creative Director)')),
                ('university', models.CharField(max_length=254, verbose_name='Okuduğun Üniversite')),
                ('major', models.CharField(max_length=254, verbose_name='Bölümün')),
                ('bio', models.TextField(verbose_name='Önyazı / Hakkımda')),
                ('profile_photo', models.FileField(upload_to='profile/', verbose_name='Profil Fotoğrafı')),
                ('specialization', models.CharField(max_length=254, verbose_name='İlerlediğin Alan (Örn: UI/UX & Dev)')),
                ('experience_level', models.CharField(max_length=254, verbose_name='Deneyim Seviyesi (Örn: Junior)')),
                ('languages', models.CharField(max_length=254, verbose_name='Diller (Virgülle ayırarak)')),
                ('cv_file', models.FileField(blank=True, upload_to='documents/', verbose_name='CV Dosyası (PDF)')),
            ],
            options={
                'verbose_name': 'Hakkımda Bilgisi',
                'verbose_name_plural': 'Hakkımda Bilgileri',
            },
        ),
    ]
