# Generated by Django 6.0.5 on 2026-05-22 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _eski_veriyi_aktar(apps):
    AboutMe = apps.get_model('myCV', 'AboutMe')
    GeneralSetting = apps.get_model('myCV', 'GeneralSetting')
    GirisBolumu = apps.get_model('myCV', 'GirisBolumu')
    Hakkimda = apps.get_model('myCV', 'Hakkimda')
    SiteAyari = apps.get_model('myCV', 'SiteAyari')

    for about in AboutMe.objects.all():
        parcalar = (about.name or '').split(' ', 1)
        GirisBolumu.objects.create(
            ad=parcalar[0],
            soyad=parcalar[1] if len(parcalar) > 1 else '',
            universite=about.university,
            bolum=about.major,
            kisa_aciklama=(about.bio or '')[:500],
            aktif=True,
        )
        Hakkimda.objects.create(
            unvan=about.title,
            eposta='ornek@mail.com',
            telefon='-',
            onyazi=about.bio or '',
            ilerledigi_alanlar=about.specialization,
            deneyim_seviyesi=about.experience_level,
            egitim_bilgileri=f'{about.university} — {about.major}',
            diller=about.languages,
            aktif=True,
        )

    for ayar in GeneralSetting.objects.all():
        SiteAyari.objects.get_or_create(
            anahtar=ayar.name,
            defaults={'aciklama': ayar.description, 'deger': ayar.parameter},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0003_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('baslangic_tarihi', models.CharField(max_length=50, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.CharField(blank=True, max_length=50, verbose_name='Bitiş Tarihi')),
                ('okul_adi', models.CharField(max_length=254, verbose_name='Okul / Üniversite')),
                ('bolum', models.CharField(max_length=254, verbose_name='Bölüm')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Eğitim Kaydı',
                'verbose_name_plural': 'Eğitim Kayıtları',
                'ordering': ('sira',),
            },
        ),
        migrations.CreateModel(
            name='GelenMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('konu', models.CharField(max_length=300, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'Gelen Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='GirisBolumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('universite', models.CharField(max_length=254, verbose_name='Okunan Üniversite')),
                ('bolum', models.CharField(max_length=254, verbose_name='Bölüm')),
                ('kisa_aciklama', models.TextField(blank=True, help_text='Hero altında görünen kısa metin.', verbose_name='Kısa Tanıtım')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Profil Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Giriş (Hero) Bilgisi',
                'verbose_name_plural': 'Giriş (Hero) Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('unvan', models.CharField(help_text='Örn: Yazılım Geliştirici', max_length=254, verbose_name='Unvan')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=30, verbose_name='Telefon')),
                ('adres', models.CharField(blank=True, max_length=500, verbose_name='Adres')),
                ('onyazi', models.TextField(verbose_name='Hakkımda Önyazısı')),
                ('ilerledigi_alanlar', models.CharField(max_length=500, verbose_name='İlerlediğim Alanlar')),
                ('deneyim_seviyesi', models.CharField(help_text='Örn: Junior, Mid-Level', max_length=100, verbose_name='Deneyim Seviyesi')),
                ('egitim_bilgileri', models.TextField(verbose_name='Eğitim Bilgileri')),
                ('diller', models.CharField(help_text='Virgülle ayırarak yazın.', max_length=500, verbose_name='Diller')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='hakkimda/', verbose_name='Profil Fotoğrafı')),
                ('cv_dosyasi', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV Dosyası (PDF)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hakkımda Bilgisi',
                'verbose_name_plural': 'Hakkımda Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('baslik', models.CharField(max_length=254, verbose_name='Hizmet Başlığı')),
                ('ikon', models.CharField(default='bi bi-star', help_text='Bootstrap Icons sınıfı. Örn: bi bi-camera', max_length=100, verbose_name='İkon Sınıfı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ('sira',),
            },
        ),
        migrations.CreateModel(
            name='IletisimBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('adres', models.CharField(max_length=500, verbose_name='Adres')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(max_length=30, verbose_name='Telefon')),
                ('harita_linki', models.URLField(blank=True, verbose_name='Harita Linki')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='IsDeneyimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('baslangic_tarihi', models.CharField(help_text='Örn: 2022 veya Ocak 2022', max_length=50, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.CharField(blank=True, help_text='Devam ediyorsa boş bırakın veya "Günümüz"', max_length=50, verbose_name='Bitiş Tarihi')),
                ('kurum_adi', models.CharField(max_length=254, verbose_name='Kurum / Şirket')),
                ('pozisyon', models.CharField(max_length=254, verbose_name='Pozisyon')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'İş Deneyimi',
                'verbose_name_plural': 'İş Deneyimleri',
                'ordering': ('sira', '-baslangic_tarihi'),
            },
        ),
        migrations.CreateModel(
            name='OzgecmisProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('profesyonel_ozet', models.TextField(verbose_name='Profesyonel Özet')),
                ('iletisim_ozeti', models.TextField(blank=True, help_text='Özgeçmiş yan panelinde görünecek iletişim metni.', verbose_name='İletişim Bilgileri Özeti')),
                ('teknik_beceriler', models.TextField(help_text='Her satıra bir beceri yazabilirsiniz.', verbose_name='Teknik Beceriler')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='ozgecmis/', verbose_name='Özgeçmiş Profil Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Özgeçmiş Profili',
                'verbose_name_plural': 'Özgeçmiş Profilleri',
            },
        ),
        migrations.CreateModel(
            name='PortfolyoProjesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('proje_adi', models.CharField(max_length=254, verbose_name='Proje Adı')),
                ('gorsel', models.ImageField(upload_to='portfolyo/', verbose_name='Proje Görseli')),
                ('kategori', models.CharField(help_text='Filtre için kullanılır. Örn: web, mobil, tasarım', max_length=100, verbose_name='Kategori')),
                ('proje_linki', models.URLField(blank=True, verbose_name='Proje Linki')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Portföy Projesi',
                'verbose_name_plural': 'Portföy Projeleri',
                'ordering': ('sira',),
            },
        ),
        migrations.CreateModel(
            name='SayisalIstatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('proje_sayisi', models.PositiveIntegerField(default=0, verbose_name='Proje Sayısı')),
                ('is_yeri_sayisi', models.PositiveIntegerField(default=0, verbose_name='Çalışılan İş Yeri Sayısı')),
                ('arastirma_raporu_sayisi', models.PositiveIntegerField(default=0, verbose_name='Araştırma Raporu Sayısı')),
                ('sertifika_sayisi', models.PositiveIntegerField(default=0, verbose_name='Sertifika Sayısı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sayısal İstatistik',
                'verbose_name_plural': 'Sayısal İstatistikler',
            },
        ),
        migrations.CreateModel(
            name='SertifikaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('sertifika_adi', models.CharField(max_length=254, verbose_name='Sertifika Adı')),
                ('veren_kurum', models.CharField(blank=True, max_length=254, verbose_name='Veren Kurum')),
                ('tarih', models.CharField(blank=True, max_length=50, verbose_name='Tarih')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikalar', to='myCV.ozgecmisprofili', verbose_name='Özgeçmiş Profili')),
            ],
            options={
                'verbose_name': 'Sertifika Kaydı',
                'verbose_name_plural': 'Sertifika Kayıtları',
                'ordering': ('sira',),
            },
        ),
        migrations.CreateModel(
            name='SiteAyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('anahtar', models.CharField(help_text='Örn: site_title, about_myself_footer', max_length=254, unique=True, verbose_name='Ayar Anahtarı')),
                ('aciklama', models.CharField(blank=True, max_length=254, verbose_name='Açıklama')),
                ('deger', models.CharField(blank=True, max_length=500, verbose_name='Değer')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
                'ordering': ('anahtar',),
            },
        ),
        migrations.CreateModel(
            name='SosyalMedyaLinki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('platform_adi', models.CharField(max_length=100, verbose_name='Platform Adı')),
                ('url', models.URLField(verbose_name='URL')),
                ('ikon_sinifi', models.CharField(default='bi bi-link-45deg', help_text='Örn: bi bi-linkedin, bi bi-github', max_length=100, verbose_name='İkon Sınıfı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Linki',
                'verbose_name_plural': 'Sosyal Medya Linkleri',
                'ordering': ('sira',),
            },
        ),
        migrations.CreateModel(
            name='Yetenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ad', models.CharField(max_length=100, verbose_name='Yetenek Adı')),
                ('yuzde', models.PositiveIntegerField(default=0, help_text='0 ile 100 arasında bir değer girin.', verbose_name='Yüzde (%)')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ('sira', 'ad'),
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('yorum_metni', models.TextField(verbose_name='Yorum')),
                ('yorumcu_adi', models.CharField(max_length=150, verbose_name='Yorumu Yapan')),
                ('yorumcu_unvan', models.CharField(blank=True, max_length=150, verbose_name='Yorumu Yapanın Unvanı')),
                ('yorum_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Yorum Tarihi')),
                ('onaylandi', models.BooleanField(default=False, help_text='Sitede yalnızca onaylanan yorumlar gösterilir.', verbose_name='Onaylandı')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ('-yorum_tarihi',),
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _eski_veriyi_aktar(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.DeleteModel(
            name='GeneralSetting',
        ),
        migrations.AddField(
            model_name='isdeneyimi',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deneyimler', to='myCV.ozgecmisprofili', verbose_name='Özgeçmiş Profili'),
        ),
        migrations.AddField(
            model_name='egitimkaydi',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitimler', to='myCV.ozgecmisprofili', verbose_name='Özgeçmiş Profili'),
        ),
    ]
