# Generated by Django 6.0.5 on 2026-05-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0004_portfoy_yeniden_yapilandirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolyoprojesi',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='portfolyo/', verbose_name='Proje Görseli'),
        ),
    ]
