# Generated by Django 6.0.5 on 2026-05-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0005_portfolyo_gorsel_opsiyonel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isdeneyimi',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='ozgecmisprofili',
            name='profesyonel_ozet',
            field=models.TextField(help_text='Özgeçmiş sayfasında görünen ana tanıtım metni.', verbose_name='Profesyonel Özet'),
        ),
        migrations.AlterField(
            model_name='ozgecmisprofili',
            name='teknik_beceriler',
            field=models.TextField(blank=True, default='', help_text='Her satıra bir beceri yazabilirsiniz. (İsteğe bağlı)', verbose_name='Teknik Beceriler'),
        ),
    ]
